/**
 *
 * $Id$
 */
package at.ac.tuwien.big.momot.examples.stack.stack.validation;

import at.ac.tuwien.big.momot.examples.stack.stack.Stack;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link at.ac.tuwien.big.momot.examples.stack.stack.StackModel}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface StackModelValidator {
	boolean validate();

	boolean validateStacks(EList<Stack> value);
}
